#!/bin/bash
# Create RAID 0 arrays
sudo mdadm --create --verbose /dev/md0 --level=0 --raid-devices=2 /dev/sdb /dev/sdc
sudo mdadm --create --verbose /dev/md1 --level=0 --raid-devices=2 /dev/sdd /dev/sde

# Create RAID 1 array using RAID 0 arrays
sudo mdadm --create --verbose /dev/md2 --level=1 --raid-devices=2 /dev/md0 /dev/md1
